Repository ember-codemods/ember-no-implicit-this-codemod, pull requests merged in 2024-01, with the labels that each got.

#405 drop support for Node < 16
  .github/workflows/tests.yml
  package.json
Labels: breaking

#409 add grouping to dependabot config
  .github/dependabot.yml
Labels: internal

#401 swap to pnpm
  .github/workflows/tests.yml
  package.json
  pnpm-lock.yaml
  yarn.lock
Labels: internal

#400 Update ember-codemods-telemetry-helpers for Mac M support
  package.json
  pnpm-lock.yaml
Labels: enhancement

#416 setup release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  CHANGELOG.md
  RELEASE.md
  package.json
  pnpm-lock.yaml
Labels: internal

#418 Typescript
  .github/workflows/tests.yml
  .gitignore
  helpers/types.ts
  package.json
  pnpm-lock.yaml
  test/helpers/sequence.ts
  test/helpers/test-runner.ts
  test/helpers/utils.ts
  test/run-test.ts
  transforms/no-implicit-this/__testfixtures__/-mock-telemetry.d.json.ts
  transforms/no-implicit-this/babel-config.js
  transforms/no-implicit-this/helpers/known-helpers.ts
  transforms/no-implicit-this/helpers/options.ts
  transforms/no-implicit-this/helpers/parse.ts
  transforms/no-implicit-this/helpers/plugin.ts
  transforms/no-implicit-this/helpers/tagged-templates.ts
  transforms/no-implicit-this/helpers/telemetry.ts
  transforms/no-implicit-this/index.js
  transforms/no-implicit-this/index.ts
  transforms/no-implicit-this/test-helpers.js
  transforms/no-implicit-this/test-helpers.ts
  transforms/no-implicit-this/test.ts
  tsconfig.json
  tsconfig.node16-strictest.json
  types/codemod-cli.d.ts
  types/ember-codemods-telemetry-helpers.d.ts
Labels: internal
